import type { Metadata } from 'next';
import { CookiesProvider } from 'next-client-cookies/server';
import { Inter } from 'next/font/google';
import ComponentsStyledRegistry from '@/systems/components.styled.antd';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <CookiesProvider>
                    <ComponentsStyledRegistry>
                        {children}
                    </ComponentsStyledRegistry>
                </CookiesProvider>
            </body>
        </html>
    );
}
